// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapp.DataAccessLayer.DBContexts;

#nullable disable

namespace aspnetapp.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20240204170335_patientdb_2")]
    partial class patientdb_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspnetapp.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2024, 2, 4, 9, 3, 35, 807, DateTimeKind.Local).AddTicks(1280));

                    b.Property<DateTime>("Dob")
                        .HasMaxLength(15)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ssn")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Zip")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 A Str",
                            City = "Somewhere",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1970, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aaa@b.com",
                            FirstName = "David",
                            LastName = "Mike",
                            MiddleName = "A",
                            Ssn = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "101 A Str",
                            City = "Somewhere",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dob = new DateTime(1972, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bbbb@b.com",
                            FirstName = "Steve",
                            LastName = "Warner",
                            MiddleName = "B",
                            Ssn = "123456788"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
