// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetapp.DataAccessLayer.DBContexts;

#nullable disable

namespace aspnetapp.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20240204165654_initialPatients")]
    partial class initialPatients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspnetapp.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            LastName = "Mike"
                        },
                        new
                        {
                            Id = -2,
                            LastName = "Warner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
